[package]
name = "delta_bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
criterion = "0.5.1"
deltaml = { path = "../delta" }

[[bench]]
name = "benchmark"
harness = false
path = "src/benchmark.rs"