[package]
name = "delta_bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deltaml = { path = "../delta" }
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "adam_benchmark"
harness = false
path = "src/adam_benchmark.rs"