[workspace]
members = [
    "delta",
    "examples/image_classification/cifar10",
    "examples/image_classification/mnist",
    "examples/image_classification/imagenet_v2",
    "examples/image_classification/custom",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
