[workspace]
members = [
    "delta_common",
    "delta_data",
    "delta_nn",
    "delta_optimizers",
    "delta_activations",
    "delta_losses",
    "delta_tensor",
    "examples/mnist",
]
resolver = "2"
