name: core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/CONTRIBUTING.md"
      - "**/.gitignore"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/.config/**"

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: cargo clippy --all-targets

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: clippy

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Project
        run: cargo build --release

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download and Cache MNIST
        uses: actions/cache@v4
        id: mnist-cache
        with:
          path: ${{ github.workspace }}/.cache/dataset/mnist
          key: ${{ runner.os }}-mnist-${{ hashFiles('**/Cargo.lock') }}

      - name: Download MNIST Data
        if: steps.mnist-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache/dataset/mnist
          cd .cache/dataset/mnist
          curl -L -O https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz
          curl -L -O https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz
          curl -L -O https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz
          curl -L -O https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz

      - name: Download and Cache CIFAR-10
        uses: actions/cache@v4
        id: cifar10-cache
        with:
          path: ${{ github.workspace }}/.cache/dataset/cifar10
          key: ${{ runner.os }}-cifar10-${{ hashFiles('**/Cargo.lock') }}

      - name: Download CIFAR-10 Data
        if: steps.cifar10-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache/dataset/cifar10
          cd .cache/dataset/cifar10
          curl -L -O https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz

      - name: Download and Cache CIFAR-100
        uses: actions/cache@v4
        id: cifar100-cache
        with:
          path: ${{ github.workspace }}/.cache/dataset/cifar100
          key: ${{ runner.os }}-cifar100-${{ hashFiles('**/Cargo.lock') }}

      - name: Download CIFAR-100 Data
        if: steps.cifar100-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache/dataset/cifar100
          cd .cache/dataset/cifar100
          curl -L -O https://www.cs.toronto.edu/~kriz/cifar-100-binary.tar.gz

      - name: Download and Cache ImageNetV2
        uses: actions/cache@v4
        id: imagenetv2-cache
        with:
          path: ${{ github.workspace }}/.cache/dataset/imagenetv2
          key: ${{ runner.os }}-imagenetv2-${{ hashFiles('**/Cargo.lock') }}

      - name: Download ImageNetV2 Data
        if: steps.imagenetv2-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache/dataset/imagenetv2
          cd .cache/dataset/imagenetv2
          curl -L -O https://huggingface.co/datasets/vaishaal/ImageNetV2/resolve/main/imagenetv2-matched-frequency.tar.gz
          curl -L -O https://huggingface.co/datasets/vaishaal/ImageNetV2/resolve/main/imagenetv2-threshold0.7.tar.gz
          curl -L -O https://huggingface.co/datasets/vaishaal/ImageNetV2/resolve/main/imagenetv2-top-images.tar.gz

      - name: Run Tests
        run: cargo test

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Coverage
        run: cargo tarpaulin --out Html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./tarpaulin-report.html
