name: machete

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Find Unused Dependencies
        id: find_dependencies
        run: |
          echo "Running cargo machete..."
          cargo machete --with-metadata
        continue-on-error: true

      - name: Check for unused dependencies
        id: check_dependencies
        run: |
          if [[ ${{ steps.find_dependencies.outcome }} == "failure" ]]; then
            echo "Unused dependencies were found."
            echo "dependencies_found=true" >> $GITHUB_ENV
          else
            echo "No unused dependencies were found."
            echo "dependencies_found=false" >> $GITHUB_ENV
          fi

      - name: Create Branch and Fix Unused Dependencies
        id: cleanup_step
        if: env.dependencies_found == 'true'
        run: |
          BRANCH_NAME="cleanup-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "Branch created: $BRANCH_NAME"
          
          # Fix dependencies using cargo machete
          cargo machete --fix

          # Check if there are changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "dmlops"
            git config --global user.email "deltaml@icloud.com"
            git add .
            git commit -m "Fix unused dependencies using cargo machete"
            git push --set-upstream origin $BRANCH_NAME
            echo "Changes committed and pushed to $BRANCH_NAME"
          else
            echo "No changes detected. No commit or push."
          fi

          # Create a pull request using GitHub CLI (gh)
          if [[ -n "$(git status --porcelain)" ]]; then
            gh pr create --base master --head $BRANCH_NAME --title "Fix Unused Dependencies" --body "This PR fixes unused dependencies found by cargo machete." --draft=false --label "dependencies, automated pr"
            echo "Pull request created."
          fi