name: machete

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Find Unused Dependencies
        id: find_dependencies
        run: |
          echo "Running cargo machete..."
          cargo machete --with-metadata
        continue-on-error: true

      - name: Check for unused dependencies
        id: check_dependencies
        run: |
          if [[ ${{ steps.find_dependencies.outcome }} == "failure" ]]; then
            echo "Unused dependencies were found."
            echo "dependencies_found=true" >> $GITHUB_ENV
          else
            echo "No unused dependencies were found."
            echo "dependencies_found=false" >> $GITHUB_ENV
          fi

      - name: Fix Unused Dependencies
        if: env.dependencies_found == 'true'
        run: cargo machete --fix
        continue-on-error: true

      - name: Check for changes
        id: check_changes
        if: env.dependencies_found == 'true'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes were made."
            echo "changes_made=true" >> $GITHUB_ENV
          else
            echo "No changes were made."
            echo "changes_made=false" >> $GITHUB_ENV
          fi

      - name: Create a new branch for the changes
        id: create_branch
        if: env.changes_made == 'true'
        run: |
          BRANCH_NAME="cleanup-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Commit Changes
        if: env.changes_made == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Fix unused dependencies using cargo machete"
          git remote set-url origin https://x-access-token:${{ secrets.DELTA_GH_TOKEN }}@github.com/${{ github.repository }}
          git push --set-upstream origin ${{ env.branch_name }}

      - name: Create Pull Request
        if: env.changes_made == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.DELTA_GH_TOKEN }}
          branch: ${{ env.branch_name }}
          base: master
          title: "Fix unused dependencies"
          body: "This PR fixes unused dependencies found by cargo machete."
          commit-message: "machete: removing unused dependencies"
          draft: "false"
          labels: "dependencies, automated pr"
          assignees: "mjovanc"